sonar.projectKey=sentinel-bfd7ff
sonar.projectName=Sentinel
sonar.projectVersion=1.0
sonar.sources=src,backend/app
sonar.language=ts,tsx,py
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**,.git/**,__pycache__/**,*.pyc,venv/**,.venv/**,tests/**,src/tests/**
sonar.typescript.exclusions=src/tests/**
sonar.python.exclusions=tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
